### ISSUE TITLE
Проверить, что между фронтом и бэком не передаётся никакой незашифрованной sensitive информации

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/ItHappened#192]

**Comment by holymosh** [comment]
версия - 1.1.0 (18)
android 8 

отправил в синхронизации json, в котором удалил два отслеживания у которых isDeleted = true , до этого менял username , после синхронизации приложение падает. Удалил, поставил, попытался зайти, опять падает. сейчас при перезапуске идет запрос на синхронизацию refresh токена. Приходит 200 потом приложение падает.

Ожидал что этого не произойдет

**Comment by holymosh** [comment]
action: создал фай точку, подключился к ней с телефона, снифил интерфейс, который является шлюзом для телефона. Зашел в приложение, зашел в свой профиль
expected result: все запросы к api гугла и к бэкенду приложения идут только по https
test result: passed

action: добавил событие, синхронизировался
expected result:запросы к бэкенду идут по https 
test result: passed

action: сменил никнэйм и синхронизировался 
expected result:запросы к бэкенду идут по https 
test result: passed

action: вышел из профиля, зашел в другой профиль
expected result:запросы к бэкенду идут по https 
test result: passed
